version: '3.8'

services:
  mysql:
    container_name: mysql-dev-container
    restart: always
    image: 'mysql'
    ports:
      - "3308:3306"
    networks:
      - dev_network
    environment:
      - 'MYSQL_ROOT_PASSWORD=Nmnmnm6@@'
      - 'MYSQL_DATABASE=mydb'

  app:
    container_name: instructor-dev-app
    restart: always
    image: 'mohamadshosha/instructorsphare'
    networks:
      - dev_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql

networks:
  dev_network:
    driver: bridge
